MinPro334_GroupA/MinPro334_GroupA/Controllers/AlamatController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MinPro334_GroupA.datamodels;
using MinPro334_GroupA.Services;
using MinPro334_GroupA.viewmodels;

namespace MinPro334_GroupA.Controllers
{
    public class AlamatController : Controller
    {
        private AlamatService alamatService;
        private LokasiService lokasiService;
        private int IdUser = 1; //

        public AlamatController(AlamatService _alamatService, LokasiService _lokasiService)
        {
            alamatService = _alamatService;
            lokasiService = _lokasiService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize, string dropDownLabel, string curentdropDownLabel)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.currentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (dropDownLabel != null)
            {
                curentdropDownLabel = dropDownLabel;

            }

            ViewBag.CurentdropDownLabel = dropDownLabel;


            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<VMLocation> data = await alamatService.GetAllData();

            //List<string> label = new List<string>();

            //foreach (var item in data)
            //{
            //    label.Add(item.Label);
            //}

            //ViewBag.listLabel = label.Distinct();


            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Label!.ToLower().Contains(searchString.ToLower())).ToList();
            }
            //if (dropDownLabel != null)
            //{
            //    data = data.Where(a => a.Label == dropDownLabel).ToList();
            //}

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Label).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Label).ToList();
                    break;
            }

            return View(PaginatedList<VMLocation>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public async Task<IActionResult> Create()
        {
            VMLocation data = new VMLocation();

            List<VMLocation> listLocation = await lokasiService.GetAllDataKecKota();
            ViewBag.listLocation = listLocation;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMLocation dataParam)
        {
            VMLocation data = await alamatService.GetBiodataId(IdUser);
            dataParam.BiodataId = data.BiodataId;

            dataParam.CreatedBy = IdUser;
            VMResponse respon = await alamatService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("index");
        }

        public async Task<IActionResult> edit(int id)
        {
            VMLocation data = await alamatService.GetDataById(id);

            List<VMLocation> listLocation = await lokasiService.GetAllDataKecKota();
            ViewBag.listLocation = listLocation;
           //ViewBag.listLocation = new SelectList(listLocation, "LocationId", "NameLocation", data.LocationId);
            
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMLocation dataParam)
        {
            dataParam.CreatedBy = IdUser;
            VMResponse respon = await alamatService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMLocation data = await alamatService.GetDataById(id);

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(long id)
        {
            VMResponse respon = await alamatService.Delete(id);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> MultipleDelete(List<int> listId)
        {
            List<string> listName = new List<string>();
            foreach (var item in listId)
            {
                VMLocation data = await alamatService.GetDataById(item);
                listName.Add(data.Label );
            }

            ViewBag.ListName = listName;
            return PartialView();
        }


        [HttpPost]
        public async Task<IActionResult> SureMultipleDelete(List<int> listId)
        {
            VMResponse respon = await alamatService.MultipleDelete(listId);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }

    }
}

MinPro334_GroupA/MinPro334_GroupA/Views/Alamat/Create.cshtml
@using MinPro334_GroupA.viewmodels;
@model VMLocation

@{
    ViewData["Title"] = "Tambah Alamat";
}


<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_input">

            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">

            <div class="mb-4 row">
                <label for="Label" class="col-sm-4 col-form-label">Label Alamat</label>
                <input type="text" class="form-control" id="Label" name="Label" value="@Model.Label">
            </div>

            <div class="mb-4 row">
                <label for="Recipient" class="col-sm-4 col-form-label">Nama Penerima</label>
                <input type="text" class="form-control" id="Recipient" name="Recipient" value="@Model.Recipient">                
            </div>

            <div class="mb-4 row">
                <label for="RecipientPhoneNumber" class="col-sm-6 col-form-label">Nomor HP Penerima</label>
                <input type="text" class="form-control" id="RecipientPhoneNumber" name="RecipientPhoneNumber" value="@Model.RecipientPhoneNumber">                
            </div>

            <div class="mb-4 row">
                <label for="LocationId" class="col-sm-6 col-form-label">Kecamatan / Kota</label>
                    @Html.DropDownList("LocationId",
                    new SelectList(ViewBag.listLocation, "LocationId", "NameLocation"),
                    "---Pilih Kecamatan/Kota---",
                    new { @class = "form-control"}
                    )
            </div>

            <div class="mb-4 row">
                <label for="PostalCode" class="col-sm-6 col-form-label">Kode Pos</label>
                <input type="text" class="form-control" id="PostalCode" name="PostalCode" value="@Model.PostalCode">
            </div>
           
            <div class="mb-4 row">
                <label for="PostalCode" class="col-sm-6 col-form-label">Alamat</label>
                <textarea class="form-control col-sm-6" id="Address" name="Address" rows="4">@Model.Address</textarea>
            </div>

            <div class="form-group row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a class="btn btn-light" asp-controller="Alamat" asp-action="Index">Batal</a>
                </div>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Label: "required",
            Recipient: "required",
            RecipientPhoneNumber: "required",
            LocationId: "required",
            Address: "required"

        },
        messages: {
            Label: "Masukan label alamat",
            Recipient: "Masukan nama penerima",
            RecipientPhoneNumber: "Masukan nomor HP penerima",
            LocationId: "Masukan Kecamatan/Kota",
            Address: "Masukan alamat"
        },
        submitHandler: function (form) {
            //debugger
            fungsiSubmit(form);
        }
    })

    function fungsiSubmit(form) {
        var dataForm = $(form).serialize();

        var id = 0

        debugger

        $.ajax({
            url: "/Alamat/Create",
            type: "post",
            data: dataForm,
            dataType: "json",
            success: function (respon) {

                var data = respon.dataRespon

                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.Message)
                }
            }
        })
    }
</script>

MinPro334_GroupA/MinPro334_GroupA/Views/Alamat/Delete.cshtml
@using MinPro334_GroupA.datamodels;
@using MinPro334_GroupA.viewmodels;

@model VMLocation

@{
    ViewData["Title"] = "HAPUS !";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post" id="form_delete">

            <input type="hidden" id="Id" name="Id" value="@Model.Id" />

            <h4>Anda Akan Menghapus Alamat @Model.Recipient ?</h4>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Ya</button>
                <a asp-controller="Alamat" asp-action="Index" class="btn btn-Light">Tidak</a>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {

            var id = $("#Id").val()

            $.ajax({
                url: "/Alamat/SureDelete",
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon

                    if (data.success) {
                        $("#my_modal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })

        }
    })
</script>

MinPro334_GroupA/MinPro334_GroupA/Views/Alamat/Edit.cshtml
@using MinPro334_GroupA.viewmodels;
@model VMLocation

@{
    ViewData["Title"] = "Edit Alamat";
}


<div class="card">
    <div class="card-body">

        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_input">

            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">

            <div class="mb-4 row">
                <label for="Label" class="col-sm-4 col-form-label">Label Alamat</label>
                <input type="text" class="form-control" id="Label" name="Label" value="@Model.Label">
            </div>

            <div class="mb-4 row">
                <label for="Recipient" class="col-sm-4 col-form-label">Nama Penerima</label>
                <input type="text" class="form-control" id="Recipient" name="Recipient" value="@Model.Recipient">
            </div>

            <div class="mb-4 row">
                <label for="RecipientPhoneNumber" class="col-sm-6 col-form-label">Nomor HP Penerima</label>
                <input type="text" class="form-control" id="RecipientPhoneNumber" name="RecipientPhoneNumber" value="@Model.RecipientPhoneNumber">
            </div>

            <div class="mb-4 row">
                <label for="LocationId" class="col-sm-6 col-form-label">Kecamatan / Kota</label>
                @Html.DropDownList("LocationId",
                new SelectList(ViewBag.listLocation, "LocationId", "NameLocation"),
                "---Pilih Kecamatan/Kota---",
                new { @class = "form-control"}
                )
            </div>

            <div class="mb-4 row">
                <label for="PostalCode" class="col-sm-6 col-form-label">Kode Pos</label>
                <input type="text" class="form-control" id="PostalCode" name="PostalCode" value="@Model.PostalCode">
            </div>

            <div class="mb-4 row">
                <label for="PostalCode" class="col-sm-6 col-form-label">Alamat</label>
                <textarea class="form-control col-sm-6" id="Address" name="Address" rows="4">@Model.Address</textarea>
            </div>

            <div class="form-group row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a class="btn btn-light" asp-controller="Alamat" asp-action="Index">Batal</a>
                </div>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Label: "required",
            Recipient: "required",
            RecipientPhoneNumber: "required",
            LocationId: "required",
            Address: "required"

        },
        messages: {
            Label: "Masukan label alamat",
            Recipient: "Masukan nama penerima",
            RecipientPhoneNumber: "Masukan nomor HP penerima",
            LocationId: "Masukan Kecamatan/Kota",
            Address: "Masukan alamat"
        },
        submitHandler: function (form) {
            //debugger
            fungsiSubmit(form);
        }
    })

    function fungsiSubmit(form) {
        var dataForm = $(form).serialize();

        var id = 0

        debugger

        $.ajax({
            url: "/Alamat/Edit",
            type: "post",
            data: dataForm,
            dataType: "json",
            success: function (respon) {

                var data = respon.dataRespon

                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.Message)
                }
            }
        })
    }
</script>

MinPro334_GroupA/MinPro334_GroupA/Views/Alamat/Index.cshtml
@using MinPro334_GroupA.viewmodels;
@model PaginatedList<VMLocation>

@{
    ViewData["Title"] = "Tab Alamat";
}

<div class="row">

    <div class="col-sm-4">

        <div class="card">
            <div>
                <h4 type="file" class="ti ti-edit" style="position:absolute;top:30px;right:70px;">&nbsp;</h4>
            </div>
            <div class="card-body text-center">
                <img src="~/Modernize-1.0.0/src/assets/images/profile/user-1.jpg" class="rounded-circle img-thumbnail" height="150" width="150">
                <h2>&nbsp;</h2>
                <h5 class="card-title">Bronze Member</h5>
                <p class="card-text">Since 2020</p>
                <h5>  &#9733;</h5>
                <h5>&nbsp;</h5>
            
            </div>

            <div style="padding-top:100px; padding-left:70px">
                <a class="p-3" style="background-color:white; color:#329fdc; font-size:large" href="/Pasien/Index">&nbsp;Pasien</a>
                <h4 class="p-3" style="background-color:white; color:#329fdc; font-size:large">&nbsp;Pembelian Obat</h4>
                <div class="card-khusus">
                </div>

                <h4 class="p-3" style="background-color:white; color:#329fdc; font-size:large">&nbsp;Rencana Kedatangan</h4>
                <div class="card-khusus">
                </div>

                <h4 class="p-3" style="background-color:white; color:#329fdc; font-size:large">&nbsp;Riwayat Chat Dokter</h4>
                <div class="card-khusus">
                </div>

                <div>
                </div>

            </div>
       
        </div>
    </div>


    <div class="col-sm-8">
        <div class="card">
            <div class="card text-center">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link" href="PasienProfil/Index">Profil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active">Alamat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul>
                </div>

                <div class="row mb-3">
                    <div class="col-12">
                        <div class="row mb-4"></div>

                        <div class="d-flex justify-content-between" style="margin: 0 1rem">
                            <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                                <div class="input-group w-100">
                                    <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="search.." />
                                    <div class="input-group-prepend">
                                        <button type="submit" class="input-group-text" title="search">
                                            <i class="ti ti-search"></i>
                                        </button>
                                    </div>
                                    <div class="input-group-prepend">
                                        <a class="input-group-text" asp-action="Index" title="reset">
                                            <i class="ti ti-refresh"></i>
                                        </a>
                                    </div>
                                </div>                  
                            </form>

                            @* <div>
                                <form name="dropDownLabel" id="form_label" asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize"
                                      asp-route-currentFilter="@ViewBag.CurrentFilter">
                                    @Html.DropDownList(
                                    "dropDownLabel", new SelectList(ViewBag.listLabel,"Label"),
                                    "--Pilih Location Level--",
                                    new { @class = "form-control"}
                                    )
                                </form>
                            </div>   *@
                            
                          @*   <form method="get">
                                <label for="sortField">Urutkan berdasarkan:</label>
                                <select id="sortField" name="sortField">
                                    <option value="recipient">Nama Penerima</option>
                                    <option value="label">Label Alamat</option>
                                </select>
                                <button type="submit">Urutkan</button>
                            </form> *@

                        </div>


                    </div>
                </div>

                <div class="d-flex justify-content-between" style="margin:0 2rem">
                    <button style="cursor:pointer; border:1px solid" class="btn btn-danger" id="btn_multiple_delete" disabled>Delete</button>
                    <div style="display:flex; align-items:center">

                        <a style="margin:0 0.5rem" 
                           asp-action="Index" 
                           asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.currentFilter"
                           asp-route-pageSize="@ViewBag.currentPageSize">
                            A-Z
                        </a>
                        <form asp-action="Index" id="form_pagesize" style="margin:0 0.5rem">
                            <select name="PageSize" id="PageSize" class="form-control">
                                <option value="3">3</option>
                                <option value="5">5</option>
                                <option value="10">10</option>
                            </select>
                        </form>
                        <button style="cursor:pointer; border:1px solid; margin:0 0.5rem" class="btn btn-primary" id="btn_create"><i class="bi-plus"></i>Create</button>
                    </div>
                </div>

                <div class="card-body border-top mt-4">
                    <table class="table table-hover mb-3">
                        <tbody>
                            @if (Model.Count != 0)
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td style="border:none; margin-right:3rem; align-self:center">
                                            <input type="checkbox" onchange="selectedItem()" class="mychecked" value="@item.Id" />
                                        </td>
                                        <td style="text-align: left;">
                                            <p><b>@item.Label</b></p>
                                            <p>@item.Recipient, @item.RecipientPhoneNumber</p>
                                            <p>@item.Address, @item.NameLocation</p>
                                        </td>
                                        <td>
                                            <a class="btn btn-success btn_edit" style="color:whitesmoke" dataid="@item.Id">Edit</a>
                                            <a class="btn btn-danger btn_delete" style="color:whitesmoke" dataid="@item.Id">Delete</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td>Data not found</td>
                                </tr>
                            }
                        </tbody>
                        
                    </table>
                </div>

                <div class="card-footer">
                    @{
                        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                    }
                    <div class="row">
          
                        <div class="col-20">
                            Page @Model.PageIndex of @Model.TotalPages
                            <a asp-action="Index"
                               asp-route-sortOrder="@ViewBag.CurrentSort"
                               asp-route-pageNumber="@(Model.PageIndex - 1)"
                               asp-route-currentFilter="@ViewBag.CurrentFilter"
                               asp-route-pageSize="@ViewBag.CurrentPageSize"
                               class="btn btn-info float-right @prevDisabled">
                                Previous
                            </a>

                            <a asp-action="Index"
                               asp-route-sortOrder="@ViewBag.CurrentSort"
                               asp-route-pageNumber="@(Model.PageIndex + 1)"
                               asp-route-currentFilter="@ViewBag.CurrentFilter"
                               asp-route-pageSize="@ViewBag.CurrentPageSize"
                               class="btn btn-info float-right @nextDisabled">
                                Next
                            </a>
                        </div>
                    </div>
                </div>
               
            </div>
        </div>


</div>

<script>
    var listId = []

    function selectedItem() {
        var mychecked = $(".mychecked")
        listId = []
        for (var i = 0; i < mychecked.length; i++) {
            if (mychecked[i].checked) {
                listId.push(mychecked[i].value)
            }
        }

        if (listId.length > 0) {
            $("#btn_multiple_delete").attr("disabled", false)
        }
        else {
            $("#btn_multiple_delete").attr("disabled", true)
        }
    }

    $("#btn_multiple_delete").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Alamat/MultipleDelete", { listId: listId })
        $("#my_modal").modal("show")
    })

    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Alamat/Create")
        $("#my_modal").modal("show")
    })

    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Alamat/Edit?id=" + id)
        $("#my_modal").modal("show")
    })

    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Alamat/Delete?id=" + id)
        $("#my_modal").modal("show") 
    })

    $("#PageSize").val(@ViewBag.CurrentPageSize)

    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })

</script>

MinPro334_GroupA/MinPro334_GroupA/Views/Alamat/MultipleDelete.cshtml
﻿
@{
    ViewData["Title"] = "Multiple Delete Alamat";
}

<div class="card">
    <div class="card-body">
        <form asp-action="SureMultipleDelete" method="post" id="form_delete">
            <h3>Are you sure for delete ?</h3>
            @foreach (var item in ViewBag.ListName)
            {
                <h4>@item</h4>
            }
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="Alamat" asp-action="Index" class="btn btn-cyan">No</a>
            </div>
        </form>
    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {

            $.ajax({
                url: '/Alamat/SureMultipleDelete',
                type: "post",
                data: { listId: listId },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#my_modal").modal("hide")
                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })
        }
    })
</script>