MinPro334_GroupA/MinPro334_GroupA/Controllers/SegmentationProductKesehatanController.cs
using Microsoft.AspNetCore.Mvc;
using MinPro334_GroupA.datamodels;
using MinPro334_GroupA.Services;
using MinPro334_GroupA.viewmodels;

namespace MinPro334_GroupA.Controllers
{
    public class SegmentationProductKesehatanController : Controller
    {
        private SegmentationProductKesehatanService segmentationProductKesehatanService;
        private int IdUser = 1;

        public SegmentationProductKesehatanController(SegmentationProductKesehatanService _segmentationProductKesehatanService)
        {
            segmentationProductKesehatanService = _segmentationProductKesehatanService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.currentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            List<MMedicalItemSegmentation> data = await segmentationProductKesehatanService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Name).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Name).ToList();
                    break;
            }

            return View(PaginatedList<MMedicalItemSegmentation>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }

        public IActionResult Create()
        {
            MMedicalItemSegmentation data = new MMedicalItemSegmentation();
            return PartialView(data);
        }

        public async Task<JsonResult> CheckNameIsExist(string name, int id)
        {
            bool isExist = await segmentationProductKesehatanService.CheckCategoryByName(name, id);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(MMedicalItemSegmentation dataParam)
        {
            dataParam.CreatedBy = (long)HttpContext.Session.GetInt32("IdUser");
            VMResponse respon = await segmentationProductKesehatanService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Edit(int id)
        {
            MMedicalItemSegmentation data = await segmentationProductKesehatanService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MMedicalItemSegmentation dataParam)
        {
            dataParam.ModifiedBy = (long)HttpContext.Session.GetInt32("IdUser");
            dataParam.ModifiedOn = DateTime.Now;
            VMResponse respon = await segmentationProductKesehatanService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Details(int id)
        {
            MMedicalItemSegmentation data = await segmentationProductKesehatanService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            MMedicalItemSegmentation data = await segmentationProductKesehatanService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(MMedicalItemSegmentation dataParam)
        {
            dataParam.DeletedBy = (long)HttpContext.Session.GetInt32("IdUser");
            VMResponse respon = await segmentationProductKesehatanService.Delete(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }
    }
}

MinPro334_GroupA/MinPro334_GroupA/Views/SegmentationProductKesehatan/Create.cshtml
@using MinPro334_GroupA.datamodels;
@model MMedicalItemSegmentation

@{
    ViewData["Title"] = "Create Segmentation Product Kesehatan";
}

<div class="card">
    <div class="card-body">

        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="Id" class="col-sm-4 col-form-label">Nama</label>
                <div>
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
                    <span id="validated_Name" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="SegmentationProductKesehatan" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>




    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            }
        },
        messages: {
            Name: {
                required: "Please fill name",
                minlength: "The name must consist of at least 3 character",
            }
        },
        submitHandler: function (form) {
            //debugger
            //console.log(form)
            var dataForm = $(form).serialize();

            var name = $("#Name").val();
            var id = 0

            $.ajax({
                url: "/SegmentationProductKesehatan/CheckNameIsExist",
                type: "get",
                data: { name: name, id: id },
                datatype: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validated_Name").text("Name is already exist")
                        return true;
                    }
                    else {
                        fungsisubmit(dataForm)
                    }
                }
            })

        }
    })

    function fungsisubmit(dataParam) {
        $.ajax({
            url: "/SegmentationProductKesehatan/Create",
            type: "post",
            data: dataParam,
            datatype: "json",
            success: function (respon) {
                var data = respon.dataRespon

                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }
            }
        })
    }

</script>

MinPro334_GroupA/MinPro334_GroupA/Views/SegmentationProductKesehatan/Delete.cshtml
@using MinPro334_GroupA.datamodels;
@model MMedicalItemSegmentation

@{
    ViewData["Title"] = "Delete Segmentation";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post" id="form_delete">

            <input type="hidden" id="Id" name="Id" value="@Model.Id" />

            <h3>Are you sure for delete @Model.Name ?</h3>

            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="SegmentationProductKesehatan" asp-action="Index" class="btn btn-Light">No</a>
            </div>

        </form>

    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {

            //var dataParam = $(form).serialize()
            var id = $("#Id").val()

            $.ajax({
                url: "/SegmentationProductKesehatan/SureDelete",
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon

                    if (data.success) {
                        $("#my_modal").modal("hide")

                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })

        }
    })
</script>

MinPro334_GroupA/MinPro334_GroupA/Views/SegmentationProductKesehatan/Edit.cshtml
@using MinPro334_GroupA.datamodels;

@model MMedicalItemSegmentation

@{
    ViewData["Title"] = "Edit Segmentation";
}

<div class="card">
    <div class="card-body">

        <form asp-action="Edit" method="post" id="form_input">

            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">


            <div class="mb-4 row">
                <label for="Id" class="col-sm-4 col-form-label">Nama</label>
                <div>
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Name">
                    <span id="validated_Name" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="SegmentationProductKesehatan" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>




    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            }
        },
        messages: {
            Name: {
                required: "Please fill name segmentation",
                minlength: "The name must consist of at least 3 character",
            }
        },
        submitHandler: function (form) {
            //debugger
            //console.log(form)
            var dataForm = $(form).serialize();

            var name = $("#Name").val();
            var id = $("#Id").val()

            $.ajax({
                url: "/SegmentationProductKesehatan/CheckNameIsExist",
                type: "get",
                data: { name: name, id: id },
                datatype: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validated_Name").text("Name is already exist")
                        return true;
                    }
                    else {
                        fungsisubmit(dataForm)
                    }
                }
            })

        }
    })

    function fungsisubmit(dataParam) {
        $.ajax({
            url: "/SegmentationProductKesehatan/Edit",
            type: "post",
            data: dataParam,
            datatype: "json",
            success: function (respon) {
                var data = respon.dataRespon

                if (data.success) {
                    $("#my_modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }
            }
        })
    }

</script>

MinPro334_GroupA/MinPro334_GroupA/Views/SegmentationProductKesehatan/Index.cshtml
@using MinPro334_GroupA.datamodels;
@using MinPro334_GroupA.viewmodels;
@model PaginatedList<MMedicalItemSegmentation>
@{
    ViewData["Title"] = "Segmen Produk Kesehatan";
}


<div class="card">
    <div class="card-body">


        <h1 class="card-title">@ViewData["Title"]</h1>


        <div class="row mb-3">
            <div class="col-12">
                <div class="d-flex justify-content-between">

                    <button id="btn_create" class="btn btn-primary">Create</button>

                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="search..." />
                            <div class="input-group-prepend">
                                <button type="submit" class="input-group-text" title="search">
                                    <i class="ti ti-search" style="height:21px"></i>
                                </button>
                            </div>
                            <div class="input-group-prepend">
                                <a class="input-group-text" asp-action="Index" title="reset">
                                    <i class="ti ti-rotate-clockwise" style="height:21px"></i>
                                </a>
                            </div>
                        </div>
                    </form>


                </div>
            </div>
        </div>

        <table class="table table-hover mb-3">
            <thead>
                <tr>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-pageSize="@ViewBag.CurrentPageSize">
                            Name Category
                        </a>
                    </th>
                    <th style="padding-left:650px">Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Name</td>
                            <td style="padding-left:650px">
                                <a style="color:beige" class="btn btn-success btn_edit" dataid="@item.Id">Edit</a>
                                <a style="color:beige" class="btn btn-primary btn_detail" dataid="@item.Id" hidden>Detail</a>
                                <a style="color:beige" class="btn btn-danger btn_delete" dataid="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>Data Not Found</td>
                    </tr>
                }
            </tbody>

        </table>



    </div>


    <div class="card-footer">
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <div class="row">
            <div class="col-8">
                @*      <form asp-action="Index" id="form_pagesize">
                <select name="PageSize" id="PageSize" class="form-control">
                <option value="3">3</option>
                <option value="5">5</option>
                <option value="10">10</option>
                </select>
                </form> *@
                Page @Model.PageIndex of @Model.TotalPages
            </div>
            <div class="col-4 row">
                <div class="col-4">
                </div>
                <div class="col-4">
                    <a asp-action="Index" asp-route-sortOrder="@ViewBag.CurrentSort" asp-route-pageNumber="@(Model.PageIndex - 1)" asp-route-currentFilter="@ViewBag.CurrentFilter" asp-route-pageSize="@ViewBag.CurrentPageSize" class="btn btn-info float-right @prevDisabled">
                        Previous
                    </a>
                </div>
                <div class="col-4">
                    <a asp-action="Index" asp-route-sortOrder="@ViewBag.CurrentSort" asp-route-pageNumber="@(Model.PageIndex + 1)" asp-route-currentFilter="@ViewBag.CurrentFilter" asp-route-pageSize="@ViewBag.CurrentPageSize" class="btn btn-info float-right @nextDisabled">
                        &#10240Next&#10240
                    </a>
                </div>
            </div>
        </div>
    </div>


</div>


<script>
    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/SegmentationProductKesehatan/Create")
        $("#my_modal").modal("show")
        $("#exampleModalLabel").text("Tambah")

    })

    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/SegmentationProductKesehatan/Edit?id=" + id)
        $("#my_modal").modal("show")
        $("#exampleModalLabel").text("Ubah")

    })

    $(".btn_detail").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/SegmentationProductKesehatan/Details?id=" + id)
        $("#my_modal").modal("show")

    })

    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/SegmentationProductKesehatan/Delete?id=" + id)
        $("#my_modal").modal("show")
        $("#exampleModalLabel").text("Hapus !")

    })

    $("#PageSize").val(@ViewBag.CurrentPageSize)

    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })


</script>