MinPro334_GroupA/MinPro334_GroupA/Controllers/ProfilDokterController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using MinPro334_GroupA.datamodels;
using MinPro334_GroupA.Services;
using MinPro334_GroupA.viewmodels;

namespace MinPro334_GroupA.Controllers
{
    public class ProfilDokterController : Controller
    {
        private ProfilDokterServices profilDokterServices;

        private readonly IWebHostEnvironment webHostEnvironment;
        private int IdUser = 1;

        public ProfilDokterController( ProfilDokterServices _profilDokterServices, IWebHostEnvironment _webHostEnvironment)
        {
            profilDokterServices = _profilDokterServices;
            webHostEnvironment = _webHostEnvironment;
        }

        //public async Task<JsonResult> GetDataById()
        //{
        //    List<VMTblProfilDokter> data = await profilDokterServices.GetDataById();
        //    return Json(data);
        //}
        public async Task<IActionResult> Index(int id)
        {
            VMTblProfilDokter data = await profilDokterServices.GetDataById(id);
            return View(data);
        }

        public string Upload(IFormFile ImageFile)
        {
            string uniqueFileName = "";

            if (ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        [HttpPost]
        public async Task<IActionResult> SaveImg(VMFoto dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.ImagePath = Upload(dataParam.ImageFile);
            }
            //dataParam.CreateBy = IdUser;
            VMResponse respon = await profilDokterServices.SaveImg(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

    }

}

MinPro334_GroupA/MinPro334_GroupA/Controllers/TindakanDokterController.cs
using Microsoft.AspNetCore.Mvc;
using MinPro334_GroupA.datamodels;
using MinPro334_GroupA.Services;
using MinPro334_GroupA.viewmodels;

namespace MinPro334_GroupA.Controllers
{
    public class TindakanDokterController : Controller
    {
        private TindakanDokterServices tindakanDokterServices;
        private readonly IWebHostEnvironment webHostEnvironment;
        private int IdUser = 1;

        public TindakanDokterController(TindakanDokterServices _tindakanDokterServices, IWebHostEnvironment _webHostEnvironment)
        {
            tindakanDokterServices = _tindakanDokterServices;
            webHostEnvironment = _webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            VMTblProfilDokter data = await tindakanDokterServices.GetDataByIdForTreatment();
            return View(data);
        }

        public IActionResult Create()
        {
            TDoctorTreatment data = new TDoctorTreatment();
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TDoctorTreatment dataParam)
        {
            VMResponse respon = await tindakanDokterServices.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return PartialView(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExist(string name, int id)
        {
            bool isExist = await tindakanDokterServices.CheckTreatmentByName(name, id);
            return Json(isExist);
        }

        public async Task<IActionResult> Delete(int id)
        {
            TDoctorTreatment data = await tindakanDokterServices.GetDataByIdTreatment(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await tindakanDokterServices.Delete(id);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }

    }
}

MinPro334_GroupA/MinPro334_GroupA/Views/TindakanDokter/Create.cshtml
@using MinPro334_GroupA.datamodels;
@model TDoctorTreatment;

@{
    ViewData["Title"] = "Create Treatment";
}


<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post"  id="form_tindakan">
            <div class="mb-4 row">
                <label for="Name" class="col-sm-4 col-form-label">Name Treatment</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Name" name="Name">
                    <span id="validated_NameTreatment" class="text-danger"></span>
                </div>
            </div>


            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="TindakanDokter" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>



<script>
    
    $("#form_tindakan").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
                minlength: 3,
            }
        },
        messages: {
            Name: {
                required: "Please fill name",
                minlength: "The name must consist of at least 3 character",
            }
        },
        submitHandler: function (form) {
          
            var dataForm = $(form).serialize();
            console.log("tes")

            var name = $("#Name").val();
            var id = 0

            $.ajax({
                url: "/TindakanDokter/CheckNameIsExist",
                type: "get",
                data: { name: name, id: id },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validated_NameTreatment").text("Name is already exist")
                        return true;
                    }
                    else {
                        fungsisubmit(dataForm)
                    }
                }
            })

        }
    })
    function fungsisubmit(dataParam) {
        $.ajax({
            url: "/TindakanDokter/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon

                if (data.success) {
                    $("#my_modal").modal("hide")

                    Swal.fire(
                        'information',
                        data.message,
                        'success'
                    ).then(function () {
                        window.location.reload()
                    })


                }
                else {
                    toastr.errorClass(data.message)
                }
            }
        })
    }

</script>

MinPro334_GroupA/MinPro334_GroupA/Views/TindakanDokter/Delete.cshtml
@using MinPro334_GroupA.datamodels;
@model TDoctorTreatment;

@{
    ViewData["Title"] = "Delete Treatment";
}

<div class="card">
    <div class="card-body">

        <form asp-action="SureDelete" method="post" id="form_delete">


            <input type="hidden" id="Id" name="Id" value="@Model.Id" />

            <h3>Are you sure for delete @Model.Name ?</h3>


            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="TindakanDokter" asp-action="Index" class="btn btn-secondary">No</a>
            </div>

        </form>
    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {

            //var dataParam = $(form).serialize()
            var id = $("#Id").val()

            $.ajax({
                url: "/TindakanDokter/SureDelete",
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon

                    if (data.success) {
                        $("#my_modal").modal("hide")

                        Swal.fire({
                            title: "Information!",
                            text: data.message,
                            icon: "success"
                        }).then((result) => {
                            // Jika pengguna menekan tombol OK, result.value akan berisi true
                            if (result.value) {
                                // Reload halaman setelah menekan tombol OK
                                window.location.reload();
                            }
                        });
                    }
                    else {

                        Swal.fire({
                            icon: 'error',
                            title: 'warning',
                            text: data.message
                        })
                        //toastr.errorClass(data.message)
                    }
                }
            })

        }
    })
</script>

MinPro334_GroupA/MinPro334_GroupA/Views/TindakanDokter/Index.cshtml
@using MinPro334_GroupA.viewmodels;
@using MinPro334_GroupA.datamodels;
@model VMTblProfilDokter
@{
    var janji = Model.ListJumlahJanji.Count() - (Model.ListJanjiCancel.Count() + Model.ListJanjiDone.Count());

}


<style>
    .btn-circle.btn-xl {
        width: 70px;
        height: 70px;
        padding: 10px 16px;
        border-radius: 100px;
        font-size: 24px;
        line-height: 1.33;
    }

    .btn-circle {
        width: 30px;
        height: 30px;
        padding: 6px 0px;
        border-radius: 12px;
        text-align: center;
        font-size: 12px;
        line-height: 1.42857;
    }

    .btn-info, .btn-info:hover, .btn-info:active, .btn-info:visited {
        background-color: #b8e4f4 !important;
        border-color:Background;
    }

</style>

<!-- As a heading -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Home &emsp;/</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Profil Dokter</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="row">

    <div class="col-sm-4">

        <div class="card">
            @* <form id="form_gambar" enctype="multipart/form-data">
            <div class="image-upload">
            <label for="file-input"> *@
            @* <img src="https://icons.iconarchive.com/icons/dtafalonso/android-lollipop/128/Downloads-icon.png" /> *@
            @*  <h3 class="bi bi-pencil-square"  syle="cursor: pointer; position:absolute;top:30px;right:70px;">&nbsp;</h3>
            </label>
            <input id="ImageFile" name="ImageFile" onclick="submitGambar()" type="file" style="display: none" />
            </div>

            </form> *@
            @*
            <a type="button" class="dropdown-item d-flex align-items-center" asp-controller="Doctor" asp-action="IndexDetail" asp-route-id="1">
            coba
            </a> *@
            <form id="form_input" enctype="multipart/form-data">
                <div style="position:absolute;top:20px;right:80px;">
                    <input type="file" accept="image/*" name="image" id="file" style="display: none;">
                    <label for="file" style="cursor: pointer;" class="ti ti-edit"></label>
                </div>
                <div class="card-body text-center">
                    <h5>&nbsp;</h5>
                    <img src="~/images/@Model.Img" class="rounded-circle" id="output" height="150" width="150">
                </div>
            </form>
            <div class="card-body text-center">
                <h5 class="card-title">@Model.NameDoctor</h5>
                <p class="card-text">@Model.Specialization</p>
                <h5>  &#9733; &#9733; &#9733; &#9733; &#9734;</h5>

            </div>
            <div style="border-top:solid lightgrey 0.05px;">
                <h5 class="p-3" style="background-color:white; color:#329fdc">Janji<a style="float:right; color:#329fdc">@janji</a></h5>
            </div>
            <div style="border-bottom:solid lightgrey 0.05px;border-top:solid lightgrey 0.05px">
                <h5 class="p-3" style="background-color:white; color:#329fdc">Obrolan / Konsultasi<a style="float:right; color:#329fdc">@Model.ListKonsultasi.Count()</a></h5>
            </div>
        </div>

        <div class="card">
            <h3 class="p-3" style="background-color:#c4e8f8; color:#329fdc">&nbsp;Tentang Saya</h3>
            <h3 class="p-3" style="background-color:white; color:#329fdc">&nbsp;Tindakan Medis</h3>
            <div class="card-khusus">
                @foreach (var item in Model.ListNameTreatment)
                {
                    <h5> &emsp;&emsp;&nbsp; - @item.NameTreatment</h5>
                }
            </div>

            <h4 class="p-3" style="background-color:white; color:#329fdc">&nbsp;Riwayat Praktek</h4>
            <div class="card-khusus">
                @foreach (var item in Model.ListNameHospital)
                {
                    <h5>&emsp;&emsp;&nbsp;&nbsp;&nbsp;@item.NameHospital</h5>
                    if (null == item.EndDate)
                    {
                        <h6>&emsp; &emsp; &emsp;&nbsp;&nbsp;&nbsp;@item.SpecializationFaskes &nbsp; <a style="float:right; padding-right:30px;">@item.StartDate.ToString("yyyy") &nbsp  -  Sekarang</a></h6>
                    }
                    else
                    {
                        <h6>&emsp; &emsp; &emsp;&nbsp;&nbsp;&nbsp;@item.SpecializationFaskes &nbsp; <a style="float:right; padding-right:30px;">@item.StartDate.ToString("yyyy") &nbsp  -  @item.EndDate.ToString("yyyy")</a></h6>
                    }
                }
            </div>

            <h3 class="p-3" style="background-color:white; color:#329fdc">&nbsp;Pendidikan</h3>
            <div class="card-khusus">

                @foreach (var item in Model.ListInstitutionName)
                {
                    <h5>&emsp;&emsp;&nbsp;&nbsp;&nbsp;@item.InstitutionName</h5>
                    <h6>&emsp; &emsp;&emsp;&nbsp;&nbsp;&nbsp; @item.Major<a style="float:right; padding-right:30px;"> @item.Lulus</a></h6>
                }
            </div>

        </div>
    </div>


    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-pills flex-column flex-sm-row">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="true" href="@Url.Action("Index", "ProfilDokter",new { id = 1 })">Spesialisasi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="true" href="#">Tindakan</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link disabled" aria-current="true" href="#" aria-disabled="true">Konsultasi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Pengaturan</a>
                    </li>
                </ul>
            </div>
            <div class="card-body d-flex justify-content-between">
                <div>
                    @foreach (var item in Model.ListNameTreatment)
                    {
                        <p>
                            <button type="button" class="btn btn-info btn_delete"  dataid="@item.TreatmentId">
                                <a style="color:#329fdc">
                                    @item.NameTreatment &emsp;&emsp;
                                    <span class="badge" style="background-color:#66b6d2">X</span>
                                </a>
                            </button>
                        </p>
                    }
                </div>
                <div class="align-self-end">
                    <button type="button" class="btn btn-primary btn-circle btn-xl p-0" id="btn_create" style=""><i class="ti ti-plus" style="font-size: 50px;"></i></button>
                </div>
            </div>
        </div>
    </div>



    <script>
        $("#btn_create").click(function () {
            $("#modal_body").empty()
            $("#modal_body").load("/TindakanDokter/Create")
            $("#my_modal").modal("show")
        })

        $(".btn_delete").click(function () {
            var id = $(this).attr("dataid")
            $("#modal_body").empty()
            $("#modal_body").load("/TindakanDokter/Delete?id=" + id)
            $("#my_modal").modal("show")
        })


    </script>